### ISSUE TITLE
Two readmes?

### ISSUE THREAD

**Issue by AKTheKnight** [yanpaulo/RestHttpClient#7]
What's the intended difference between README.md and Source/Readme.txt?

Why not just have the root README.md?

**Comment by yanpaulo** [comment]
Source/Readme.txt is the file which appears after the user adds the Nuget package in the project on VS, but thinking about it, looks unecessary. Will remove it!

**Comment by yanpaulo** [comment]
Additional readme removed on 9bf86424479c551fec195349905890a8f4effb13
